apiVersion: v1
kind: Service
metadata:
  name: nginx-app-service
  labels:
    app: nginx-app 
spec:
  selector:
    app: nginx-app

  ports:
    - port: 8080
      targetPort: 8080

  type: NodePort
